# This is a basic workflow to help you get started with Actions

name: CI

# jobs触发条件
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 多个作业
jobs:
  # 打印版本信息
  print_version:
    # 运行时的基础环境
    runs-on: ubuntu-latest

    # 每一个 - 代表着一个步骤 Step
    steps:
      - name: version
        run: |
             echo $PATH
             node -v
